apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: devops-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: backend
          image: ghcr.io/dragos-radu/devops-dashboard-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_HOST
              value: database
            - name: POSTGRES_PORT
              value: "5432"
          envFrom:
            - secretRef:
                name: database-secret
            - secretRef:
                name: icloud-credentials
