apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: devops-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: postgres:16
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: database-secret
          volumeMounts:
            - name: database-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: database-storage
          persistentVolumeClaim:
            claimName: database-pvc